// packages/canvas-party-react/src/components/CanvasParty.tsx
import { useEffect, useRef } from 'react'
import _ from 'lodash'
import React from 'react'
import { useCanvasParty } from '../../../core/lib'
import { TTemplates } from '../../../core/src/types'

interface ICanvasPartyProps {
  colors?: string[]
  count?: number
}

type TProps = {
  options?: ICanvasPartyProps
  type: TTemplates
}

const CanvasParty: React.FunctionComponent<TProps> = ({ options, type }) => {
  const canvasWrapperRef = useRef<any>()
  const uniqId = _.uniqueId('canvas_')

  useEffect(() => {
    if (!canvasWrapperRef.current) return
    const cp = useCanvasParty(canvasWrapperRef.current, {
      type,
      ...options,
    })
    if (canvasWrapperRef.current.hasChildNodes()) {
      canvasWrapperRef.current.innerHTML = null
    }
    canvasWrapperRef.current.appendChild(cp.canvas)
    cp.setCanvasParty(type)

    return () => cp.removeCanvas()
  }, [type, options])

  return (
    <div ref={canvasWrapperRef} id={uniqId} className="canvas-wrapper"></div>
  )
}

export default CanvasParty

// packages/canvas-party-vue/src/components/CanvasParty.vue
<script setup lang="ts">
import { defineProps, ref, watch, onMounted, onUnmounted } from 'vue'
import _ from 'lodash'
// import { useCanvasParty } from '../../../core/lib'
import { useCanvasParty } from '../../../core/lib'

import { TTemplates } from '../../../core/src/types'

const props = defineProps<{
  type: TTemplates
  options?: { colors?: string[]; count?: number }
}>()

const uniqId = _.uniqueId('canvas_')
const canvasParty = ref<any>(null)

onMounted(() => {
  const wrapper = document.getElementById(uniqId) as HTMLDivElement
  canvasParty.value = useCanvasParty(wrapper, {
    type: props.type,
    ...props.options,
  })
  wrapper.appendChild(canvasParty.value.canvas)
})

watch(
  () => props.type,
  type => {
    canvasParty.value.removeCanvas()
    canvasParty.value.setCanvasParty(type)
  }
)

onUnmounted(() => {
  canvasParty.value.removeCanvas()
})
</script>

<template>
  <div class="canvas-wrapper" :id="uniqId"></div>
</template>
