// packages/canvas-party-react/src/components/CanvasParty.tsx
import { useState , useEffect, useRef} from 'react'
import { createCanvasParty } from '../../../core/lib'
type canvasPartyType  = 'confetti' | 'fireworks' | 'starfield' | 'trippy'

interface  ICanvasPartyProps  {
    type: canvasPartyType,
     options?: {
        colors?: string[],
         count?: number }
        }

type TProps = {
    canvasOptions: ICanvasPartyProps
}


function CanvasParty( {canvasOptions } :TProps ) {
    const canvasWrapperRef = useRef<any>()
    
    useEffect(() => {   
        if(!canvasWrapperRef.current) return
        const canvas = createCanvasParty(canvasWrapperRef.current, { type:  canvasOptions.type, ...canvasOptions.options})
        if(canvasWrapperRef.current.hasChildNodes()) {
            canvasWrapperRef.current.innerHTML = null
        }
        canvasWrapperRef.current.appendChild(canvas)
        

    },[canvasOptions])
    
    return ( 
       <div ref={canvasWrapperRef} className='canvas-wraper'></div>
    )
}

export default CanvasParty;

// packages/canvas-party-vue/src/CanvasParty.vue

<template>
    <div class="canvas-wraper" id="canvas-party-wraper">
    </div>
</template>


<script  setup lang='ts'>
import { defineProps, ref, onMounted } from 'vue'
import { createCanvasParty } from '../../core/lib';
const props = defineProps<{
    type: 'confetti' | 'fireworks' | 'starfield' | 'trippy',
    options?: { colors?: string[], count?: number }
}>()
// const canvasWraper = ref(null)
const canvasParty = ref<HTMLCanvasElement | null>(null)


onMounted(() => {
    const wraper = document.getElementById('canvas-party-wraper')
    canvasParty.value = createCanvasParty(wraper!, { type: props.type, ...props.options })
    wraper!.appendChild(canvasParty.value)
})


</script>

<style lang='scss'>

</style>
